---
title: "China COVID-19 Analysis"
author: "David J Jackson"
date: "Apr. 26, 2020 3:55 PM/EDT"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
     fig.width=9, fig.height=6 ) 
library(tidyverse)
library(plotly)
library(RSQLite)
theme_set(theme_light())
```
```{r,echo=FALSE}
rm(list=ls())
#these libraries are necessary
#create the URL where the dataset is stored with automatic upDates every day
db <- dbConnect(SQLite(), dbname="../COVIDDB/CORVID.sqlite3")
```
```{r,echo=FALSE}
CHINA <- dbGetQuery(db, "SELECT Countries,Reported,Cases,Deaths FROM ECDC 
                 WHERE Countries ='China'")
CHINA$Reported <- as.Date(CHINA$Reported)

```

## CHINA Cases  and Deaths by Date 
 * Data Source: European Centre for Disease Prevention and Control
 * URL: https://www.ecdc.europa.eu/en/publications-data/download-todays-data-geographic-distribution-covid-19-cases-worldwide

```{r,echo=FALSE}
CHINA$Cases <- na.omit(CHINA$Cases)
china_cases <-CHINA %>% ggplot() +
  geom_col(aes(x=Reported,y=Cases)) +
  theme(axis.text.x = element_text(angle = 45)) +
      labs(title="CHINA: COVID-19: Daily Cases by Date",y="Log of Cases") +
     scale_y_log10()

ggplotly(china_cases)
```
```{r}
    
CHINA$Deaths <- na.omit(CHINA$Deaths)
china_deaths <-CHINA  %>%  ggplot() + geom_col(aes(x=Reported,y=Deaths,fill=Deaths)) +
  theme(axis.text.x = element_text(angle = 45)) +
      labs(x="Date Reported",y="Log Deaths",title="COVID-19: Deaths by Date") +
            scale_y_log10()

ggplotly(china_deaths)           



```


### CHINA Accumulated Daily Total: Cases and Deaths
* Data Source: John Hopkins CoronavirCHINA Resource Center
* URL: https://coronavirCHINA.jhu.edu/map.html


```{r,echo=FALSE}
JHU_CHINA<- dbGetQuery(db, "SELECT country,Date,confirmed,deaths,recovered FROM JHUDATA
                     WHERE country='China';")
colnames(JHU_CHINA) <- c("Countries","Date","Cases","Deaths","Recovered")
JHU_CHINA$Date <- as.Date(JHU_CHINA$Date) 
```

```{r,echo=FALSE}
JHU_CHINA %>% 
  ggplot() + geom_col(aes(x=Date,y=na.omit(Cases),fill=Cases)) +
  theme(axis.text.x = element_text(angle = 45)) +
      labs(title="China COVID-19: Accumulated Total (Confirmed) Cases by Date",x="Date Reported",y="Total Cases")  +  scale_y_log10() +
  scale_fill_gradient(labels = scales::comma)


```
```{r,echo=FALSE}

acc_4 <- JHU_CHINA  %>%
    ggplot() + geom_col(aes(x=Date,y=Deaths,fill=Deaths)) +
  theme(axis.text.x = element_text(angle = 45)) +
      labs(title="China COVID-19: Total  Deaths by Date",x="Date Reported",y="Total Deaths") +   scale_y_log10() + scale_fill_gradient(labels = scales::comma)
ggplotly(acc_4)
```

### CHINA Recoveries Accoumliated  and Daily

```{r} 
JHU_CHINA %>% 
  ggplot() + geom_col(aes(x=Date,y=na.omit(Recovered),fill=Recovered)) +
  theme(axis.text.x = element_text(angle = 45)) +
      labs(title="China COVID-19: Accumulated  Recoveries by Date",x="Date Reported",y="Total Cases")   +
  scale_fill_gradient(labels = scales::comma) + scale_y_log10()
```

```{r}

JHU_CHINA  %>%
  ggplot() + geom_col(aes(x=Date,y=na.omit(Recovered),fill=Recovered)) +
  theme(axis.text.x = element_text(angle = 45)) +
      labs(title="CHINAA COVID-19: Accumulated  Recoveries by Date",x="Date Reported",y="Total Cases")  + scale_y_continuous(labels = scales::comma) +
  scale_fill_gradient(labels = scales::comma) + scale_y_log10()
```






